name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Compile LateX
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          # Path of Tex File
          tex_path: main.tex
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          push: yes# optional, default is no
      
