name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: xelatex GitHub Action
        uses: marcomicera/xelatex-action@v0.6
        with:
          # Path of Tex File
          input-file: main.tex # optional
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
        
      
